title: YanshuSong | Daniel
url: "https://Danielsong001.com"
baseurl: "/page"

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: yes
footer_url: "https://github.com/ankitsultana"
footer_text: "Page design by Ankit Sultana"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "/researcher/"
 - name: "Resume"
   link: "resume.pdf"
 - name: "Patent-Arm"
   link: "A kind of 6-DOF Bionic Manipulator Arm-CN201811515893-Published.pdf"
 - name: "Patent-Robot"
   link: "A Novel Kind of Double-arm Robot for Nursing Tasks-CN201811515894-Published.pdf"
 - name: "ICIA"
   link: "A Virtual Experiment Platform for 2D Robot Autonomous.pdf"
 - name: "Robio"
   link: "A Novel Heavy-Load Nursing Robotic Arm - Design and Safety Control Based on Tactile Skin.pdf"
 - name: "IEEE Sensor J"
   link: "Torque Estimation for Robotic Joint With Harmonic.pdf"
